export const QUICK_PROMPTS = [
    "Show market size trends for GLP-1 agonists in obesity.",
    "Compare Novo Nordisk vs Eli Lilly market share over 5 years.",
    "Display patents expiring in the next 5 years.",
    "Filter clinical trials recruiting in Phase 2b.",
    "Show top 5 molecules with highest CAGR.",
    "Visualize competitor pipeline for GLP-1 agonists.",
    "Show geographic distribution of obesity prevalence.",
    "Highlight high-risk patents with potential legal issues.",
    "Display sentiment trends from social media posts.",
    "Forecast market growth for next 3 years.",
    "Show number of active clinical trials by sponsor.",
    "Highlight underrepresented regions for market entry.",
    "Compare oral vs injectable formulations in market share.",
    "Display trial phase progression timelines.",
    "Highlight patents with low FTF risk.",
    "Show top competitors’ logos with market share badges.",
    "Filter clinical trials by sponsor name.",
    "Display emerging research topics in obesity management.",
    "Show price vs market penetration correlation.",
    "Highlight regions with low competitor presence.",
    "Display top news sentiment about Novo Nordisk.",
    "Show predicted CAGR by molecule class.",
    "Highlight trials with recruitment delays.",
    "Compare patent expiry risk across companies.",
    "Show interactive charts of therapy area trends.",
    "Display total number of ongoing vs planned trials.",
    "Highlight molecules with multiple ongoing trials.",
    "Show AI Agent recommendations for product launch.",
    "Filter patents by expiry date and risk level.",
    "Show historical market size vs forecast with trend arrows.",
    "Highlight competitor pipeline gaps.",
    "Compare patient sentiment vs market penetration."
];