import React, { useState } from 'react';

const sampleReportData = {
  title: 'GLP-1 Agonist Market Intelligence Report',
  subtitle: 'Comprehensive Analysis for Obesity Therapeutics',
  generatedDate: '2024-12-10',
  pages: 24,
  sections: [
    { name: 'Executive Summary', pages: '1-2' },
    { name: 'Market Overview', pages: '3-6' },
    { name: 'Competitive Landscape', pages: '7-10' },
    { name: 'Patent Analysis', pages: '11-14' },
    { name: 'Clinical Pipeline', pages: '15-18' },
    { name: 'Strategic Recommendations', pages: '19-22' },
    { name: 'Appendix & Data Sources', pages: '23-24' },
  ],
};

const generatePDFContent = () => {
  return `%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>
endobj
4 0 obj
<< /Length 650 >>
stream
BT
/F1 24 Tf
50 700 Td
(GLP-1 Agonist Market Intelligence Report) Tj
/F1 14 Tf
0 -30 Td
(CureCoders AI - Comprehensive Analysis for Obesity Therapeutics) Tj
/F1 12 Tf
0 -50 Td
(Generated: December 10, 2024) Tj
0 -40 Td
(EXECUTIVE SUMMARY) Tj
/F1 10 Tf
0 -25 Td
(Market Size: $12.4B \\(2024\\) with 23.5% CAGR through 2030) Tj
0 -15 Td
(Key Players: Novo Nordisk \\(62%\\), Eli Lilly \\(28%\\), Others \\(10%\\)) Tj
0 -15 Td
(Active Trials: 47 across Phase 1-3) Tj
0 -15 Td
(Patent Cliff: Core semaglutide patents expire April 2026) Tj
0 -30 Td
(KEY INSIGHTS FROM 7 AI AGENTS) Tj
0 -20 Td
(- IQVIA Agent: GLP-1 market growing at 23.5% CAGR) Tj
0 -15 Td
(- Patent Agent: 12 high-value FTF opportunities identified) Tj
0 -15 Td
(- Clinical Agent: 8 novel MOA trials in Phase 2+) Tj
0 -15 Td
(- EXIM Agent: China API dependency at 78%) Tj
0 -15 Td
(- Web Agent: Positive sentiment at 0.72) Tj
0 -30 Td
(Generated by CureCoders Multi-Agent AI Platform) Tj
ET
endstream
endobj
5 0 obj
<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>
endobj
xref
0 6
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000266 00000 n 
0000000970 00000 n 
trailer
<< /Size 6 /Root 1 0 R >>
startxref
1049
%%EOF`;
};

const generateExcelXML = () => {
  return `<?xml version="1.0"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">
 <Styles>
  <Style ss:ID="Header">
   <Font ss:Bold="1" ss:Size="12"/>
   <Interior ss:Color="#4F46E5" ss:Pattern="Solid"/>
   <Font ss:Color="#FFFFFF"/>
  </Style>
  <Style ss:ID="Title">
   <Font ss:Bold="1" ss:Size="16"/>
  </Style>
 </Styles>
 <Worksheet ss:Name="Market Data">
  <Table>
   <Row><Cell ss:StyleID="Title"><Data ss:Type="String">GLP-1 Agonist Market Data - CureCoders AI</Data></Cell></Row>
   <Row></Row>
   <Row>
    <Cell ss:StyleID="Header"><Data ss:Type="String">Metric</Data></Cell>
    <Cell ss:StyleID="Header"><Data ss:Type="String">Value</Data></Cell>
    <Cell ss:StyleID="Header"><Data ss:Type="String">Source</Data></Cell>
   </Row>
   <Row>
    <Cell><Data ss:Type="String">Market Size 2024</Data></Cell>
    <Cell><Data ss:Type="String">$12.4B</Data></Cell>
    <Cell><Data ss:Type="String">IQVIA Agent</Data></Cell>
   </Row>
   <Row>
    <Cell><Data ss:Type="String">CAGR 2024-2030</Data></Cell>
    <Cell><Data ss:Type="String">23.5%</Data></Cell>
    <Cell><Data ss:Type="String">IQVIA Agent</Data></Cell>
   </Row>
   <Row>
    <Cell><Data ss:Type="String">Active Clinical Trials</Data></Cell>
    <Cell><Data ss:Type="Number">47</Data></Cell>
    <Cell><Data ss:Type="String">Clinical Trials Agent</Data></Cell>
   </Row>
   <Row>
    <Cell><Data ss:Type="String">Patents Expiring 2025-2027</Data></Cell>
    <Cell><Data ss:Type="Number">12</Data></Cell>
    <Cell><Data ss:Type="String">Patent Agent</Data></Cell>
   </Row>
   <Row>
    <Cell><Data ss:Type="String">China API Dependency</Data></Cell>
    <Cell><Data ss:Type="String">78%</Data></Cell>
    <Cell><Data ss:Type="String">EXIM Agent</Data></Cell>
   </Row>
  </Table>
 </Worksheet>
 <Worksheet ss:Name="Competitors">
  <Table>
   <Row>
    <Cell ss:StyleID="Header"><Data ss:Type="String">Company</Data></Cell>
    <Cell ss:StyleID="Header"><Data ss:Type="String">Market Share</Data></Cell>
    <Cell ss:StyleID="Header"><Data ss:Type="String">Key Product</Data></Cell>
    <Cell ss:StyleID="Header"><Data ss:Type="String">Pipeline Count</Data></Cell>
   </Row>
   <Row>
    <Cell><Data ss:Type="String">Novo Nordisk</Data></Cell>
    <Cell><Data ss:Type="String">62%</Data></Cell>
    <Cell><Data ss:Type="String">Wegovy/Ozempic</Data></Cell>
    <Cell><Data ss:Type="Number">8</Data></Cell>
   </Row>
   <Row>
    <Cell><Data ss:Type="String">Eli Lilly</Data></Cell>
    <Cell><Data ss:Type="String">28%</Data></Cell>
    <Cell><Data ss:Type="String">Mounjaro/Zepbound</Data></Cell>
    <Cell><Data ss:Type="Number">11</Data></Cell>
   </Row>
   <Row>
    <Cell><Data ss:Type="String">Others</Data></Cell>
    <Cell><Data ss:Type="String">10%</Data></Cell>
    <Cell><Data ss:Type="String">Various</Data></Cell>
    <Cell><Data ss:Type="Number">28</Data></Cell>
   </Row>
  </Table>
 </Worksheet>
 <Worksheet ss:Name="Patents">
  <Table>
   <Row>
    <Cell ss:StyleID="Header"><Data ss:Type="String">Patent Title</Data></Cell>
    <Cell ss:StyleID="Header"><Data ss:Type="String">Owner</Data></Cell>
    <Cell ss:StyleID="Header"><Data ss:Type="String">Expiry Date</Data></Cell>
    <Cell ss:StyleID="Header"><Data ss:Type="String">FTF Risk</Data></Cell>
   </Row>
   <Row>
    <Cell><Data ss:Type="String">Semaglutide Composition</Data></Cell>
    <Cell><Data ss:Type="String">Novo Nordisk</Data></Cell>
    <Cell><Data ss:Type="String">Apr 2026</Data></Cell>
    <Cell><Data ss:Type="String">High</Data></Cell>
   </Row>
   <Row>
    <Cell><Data ss:Type="String">Tirzepatide Dual Agonist</Data></Cell>
    <Cell><Data ss:Type="String">Eli Lilly</Data></Cell>
    <Cell><Data ss:Type="String">Dec 2028</Data></Cell>
    <Cell><Data ss:Type="String">Medium</Data></Cell>
   </Row>
   <Row>
    <Cell><Data ss:Type="String">Oral Semaglutide Formulation</Data></Cell>
    <Cell><Data ss:Type="String">Novo Nordisk</Data></Cell>
    <Cell><Data ss:Type="String">Jun 2031</Data></Cell>
    <Cell><Data ss:Type="String">Low</Data></Cell>
   </Row>
  </Table>
 </Worksheet>
</Workbook>`;
};

const generatePPTHTML = () => {
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>GLP-1 Market Intelligence - CureCoders Presentation</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 0; padding: 0; }
    .slide { width: 100%; min-height: 100vh; padding: 60px; box-sizing: border-box; page-break-after: always; }
    .slide-1 { background: linear-gradient(135deg, #4F46E5, #06B6D4); color: white; }
    .slide-2 { background: #f8fafc; }
    .slide-3 { background: linear-gradient(135deg, #10B981, #059669); color: white; }
    .slide-4 { background: #f8fafc; }
    .slide-5 { background: linear-gradient(135deg, #8B5CF6, #EC4899); color: white; }
    h1 { font-size: 48px; margin-bottom: 20px; }
    h2 { font-size: 36px; margin-bottom: 30px; }
    .subtitle { font-size: 24px; opacity: 0.9; }
    .metric { display: inline-block; margin: 20px; padding: 30px; background: rgba(255,255,255,0.2); border-radius: 12px; text-align: center; }
    .metric-value { font-size: 48px; font-weight: bold; }
    .metric-label { font-size: 18px; opacity: 0.9; }
    .list { font-size: 24px; line-height: 2; }
    .footer { position: absolute; bottom: 30px; font-size: 14px; opacity: 0.7; }
    .agents { display: flex; flex-wrap: wrap; gap: 20px; margin-top: 30px; }
    .agent-box { background: rgba(255,255,255,0.1); padding: 20px; border-radius: 8px; flex: 1; min-width: 200px; }
  </style>
</head>
<body>
  <div class="slide slide-1">
    <h1>GLP-1 Agonist Market Intelligence</h1>
    <p class="subtitle">Comprehensive Analysis for Obesity Therapeutics</p>
    <p class="subtitle" style="margin-top: 40px;">Powered by CureCoders Multi-Agent AI Platform</p>
    <div style="margin-top: 60px;">
      <div class="metric"><div class="metric-value">$12.4B</div><div class="metric-label">Market Size 2024</div></div>
      <div class="metric"><div class="metric-value">23.5%</div><div class="metric-label">CAGR</div></div>
      <div class="metric"><div class="metric-value">47</div><div class="metric-label">Active Trials</div></div>
    </div>
    <p class="footer">Generated by CureCoders AI | December 2024</p>
  </div>

  <div class="slide slide-2">
    <h2 style="color: #4F46E5;">Market Overview - IQVIA Agent Insights</h2>
    <div class="list" style="color: #1e293b;">
      <p>• GLP-1 agonist market valued at $12.4B in 2024</p>
      <p>• Projected to reach $45.7B by 2030 (23.5% CAGR)</p>
      <p>• Novo Nordisk leads with 62% market share</p>
      <p>• Eli Lilly growing rapidly with Tirzepatide success</p>
      <p>• Obesity indication driving 67% of growth</p>
      <p>• North America represents 58% of global market</p>
    </div>
  </div>

  <div class="slide slide-3">
    <h2>Patent Landscape - Patent Agent Findings</h2>
    <div class="list">
      <p>• Core Semaglutide patents expire April 2026</p>
      <p>• 12 high-value FTF opportunities identified</p>
      <p>• $45B+ at-risk revenue from patent cliffs</p>
      <p>• Oral formulation patents extend to 2031</p>
      <p>• Novel delivery mechanisms offer patent extension paths</p>
    </div>
    <div style="margin-top: 40px; background: rgba(255,255,255,0.2); padding: 30px; border-radius: 12px;">
      <strong>Strategic Recommendation:</strong> Focus on novel delivery systems (oral, implant, patch) for competitive differentiation beyond composition patents.
    </div>
  </div>

  <div class="slide slide-4">
    <h2 style="color: #4F46E5;">Clinical Pipeline - Clinical Trials Agent</h2>
    <div class="list" style="color: #1e293b;">
      <p>• 47 active trials across GLP-1 related compounds</p>
      <p>• 12 trials in Phase 3 (late-stage)</p>
      <p>• 23 trials in Phase 2</p>
      <p>• 8 novel mechanisms of action in development</p>
      <p>• Triple agonists showing superior efficacy signals</p>
    </div>
    <div style="margin-top: 30px; padding: 20px; background: #fef3c7; border-left: 4px solid #f59e0b; color: #92400e;">
      <strong>Key Insight:</strong> Triple agonists (GLP-1/GIP/Glucagon) may become market disruptors by 2027.
    </div>
  </div>

  <div class="slide slide-5">
    <h2>Strategic Recommendations</h2>
    <div class="agents">
      <div class="agent-box">
        <h3>Short Term (0-12 mo)</h3>
        <p>• Initiate FTF filings for Semaglutide biosimilar</p>
        <p>• Secure alternative API suppliers</p>
      </div>
      <div class="agent-box">
        <h3>Medium Term (1-3 yr)</h3>
        <p>• Develop oral delivery platform</p>
        <p>• Pursue triple agonist partnerships</p>
      </div>
      <div class="agent-box">
        <h3>Long Term (3-5 yr)</h3>
        <p>• Build obesity franchise</p>
        <p>• Expand to emerging markets</p>
      </div>
    </div>
    <p class="footer">CureCoders AI - Your Pharmaceutical Intelligence Partner</p>
  </div>
</body>
</html>`;
};

const ReportsDemo: React.FC = () => {
  const [isGenerating, setIsGenerating] = useState<string | null>(null);

  const handleDownloadPDF = () => {
    setIsGenerating('pdf');
    setTimeout(() => {
      const pdfContent = generatePDFContent();
      const blob = new Blob([pdfContent], { type: 'application/pdf' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'CureCoders_GLP1_Market_Report.pdf';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      setIsGenerating(null);
    }, 1500);
  };

  const handleDownloadExcel = () => {
    setIsGenerating('excel');
    setTimeout(() => {
      const excelContent = generateExcelXML();
      const blob = new Blob([excelContent], { type: 'application/vnd.ms-excel' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'CureCoders_GLP1_Market_Data.xls';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      setIsGenerating(null);
    }, 1500);
  };

  const handleDownloadPPT = () => {
    setIsGenerating('ppt');
    setTimeout(() => {
      const pptContent = generatePPTHTML();
      const blob = new Blob([pptContent], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'CureCoders_GLP1_Presentation.html';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      setIsGenerating(null);
    }, 1500);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-indigo-900 py-12">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-12">
          <h1 className="font-display text-4xl sm:text-5xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 via-blue-400 to-purple-400">
            Report Generation Demo
          </h1>
          <p className="mt-4 text-lg text-slate-300 max-w-3xl mx-auto">
            CureCoders generates comprehensive PDF, Excel, and PowerPoint reports synthesizing insights from all AI agents. 
            Download sample reports below.
          </p>
        </div>

        <div className="grid lg:grid-cols-3 gap-6 mb-12">
          <div className="bg-slate-800/50 backdrop-blur-sm rounded-2xl shadow-xl overflow-hidden border border-slate-700">
            <div className="bg-gradient-to-r from-red-600 to-red-700 p-6">
              <div className="flex items-center gap-4">
                <div className="w-16 h-16 bg-white rounded-lg flex items-center justify-center shadow-lg">
                  <svg className="w-10 h-10 text-red-600" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8l-6-6zM6 20V4h7v5h5v11H6z"/>
                    <path d="M8 12h8v2H8zm0 4h8v2H8z"/>
                  </svg>
                </div>
                <div>
                  <h2 className="text-xl font-bold text-white">PDF Report</h2>
                  <p className="text-red-100">Professional document</p>
                </div>
              </div>
            </div>

            <div className="p-6">
              <div className="border border-slate-600 rounded-lg p-4 mb-4 bg-slate-900/50">
                <h3 className="font-bold text-white mb-1">{sampleReportData.title}</h3>
                <p className="text-sm text-slate-400 mb-3">{sampleReportData.subtitle}</p>
                <div className="flex items-center gap-4 text-xs text-slate-400">
                  <span>{sampleReportData.pages} pages</span>
                </div>
              </div>

              <h4 className="font-semibold text-slate-300 mb-3">Contents</h4>
              <ul className="space-y-2 mb-6">
                {sampleReportData.sections.slice(0, 4).map((section, idx) => (
                  <li key={idx} className="flex justify-between text-sm">
                    <span className="text-slate-300">{section.name}</span>
                    <span className="text-slate-500">p. {section.pages}</span>
                  </li>
                ))}
              </ul>

              <button
                onClick={handleDownloadPDF}
                disabled={isGenerating !== null}
                className="w-full py-3 bg-red-600 hover:bg-red-700 text-white font-semibold rounded-lg transition disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
              >
                {isGenerating === 'pdf' ? (
                  <>
                    <svg className="animate-spin w-5 h-5" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                    </svg>
                    Generating...
                  </>
                ) : (
                  <>
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                    Download PDF
                  </>
                )}
              </button>
            </div>
          </div>

          <div className="bg-slate-800/50 backdrop-blur-sm rounded-2xl shadow-xl overflow-hidden border border-slate-700">
            <div className="bg-gradient-to-r from-green-600 to-green-700 p-6">
              <div className="flex items-center gap-4">
                <div className="w-16 h-16 bg-white rounded-lg flex items-center justify-center shadow-lg">
                  <svg className="w-10 h-10 text-green-600" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8l-6-6zM6 20V4h7v5h5v11H6z"/>
                    <path d="M8 13h2v4H8zm4-2h2v6h-2zm4-4h2v10h-2z"/>
                  </svg>
                </div>
                <div>
                  <h2 className="text-xl font-bold text-white">Excel Export</h2>
                  <p className="text-green-100">Raw data workbook</p>
                </div>
              </div>
            </div>

            <div className="p-6">
              <div className="border border-slate-600 rounded-lg p-4 mb-4 bg-slate-900/50">
                <h3 className="font-bold text-white mb-1">GLP1_Market_Data.xlsx</h3>
                <p className="text-sm text-slate-400 mb-3">Multi-sheet workbook</p>
                <div className="flex items-center gap-4 text-xs text-slate-400">
                  <span>3 worksheets</span>
                  <span>~50 data rows</span>
                </div>
              </div>

              <h4 className="font-semibold text-slate-300 mb-3">Worksheets</h4>
              <ul className="space-y-2 mb-6">
                <li className="flex justify-between text-sm border-b border-slate-700 pb-2">
                  <span className="text-slate-300">Market_Data</span>
                  <span className="text-slate-500">Key metrics</span>
                </li>
                <li className="flex justify-between text-sm border-b border-slate-700 pb-2">
                  <span className="text-slate-300">Competitors</span>
                  <span className="text-slate-500">Analysis</span>
                </li>
                <li className="flex justify-between text-sm">
                  <span className="text-slate-300">Patents</span>
                  <span className="text-slate-500">Landscape</span>
                </li>
              </ul>

              <button
                onClick={handleDownloadExcel}
                disabled={isGenerating !== null}
                className="w-full py-3 bg-green-600 hover:bg-green-700 text-white font-semibold rounded-lg transition disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
              >
                {isGenerating === 'excel' ? (
                  <>
                    <svg className="animate-spin w-5 h-5" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                    </svg>
                    Generating...
                  </>
                ) : (
                  <>
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                    Download Excel
                  </>
                )}
              </button>
            </div>
          </div>

          <div className="bg-slate-800/50 backdrop-blur-sm rounded-2xl shadow-xl overflow-hidden border border-slate-700">
            <div className="bg-gradient-to-r from-orange-500 to-amber-600 p-6">
              <div className="flex items-center gap-4">
                <div className="w-16 h-16 bg-white rounded-lg flex items-center justify-center shadow-lg">
                  <svg className="w-10 h-10 text-orange-600" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm0 16H5V5h14v14z"/>
                    <path d="M7 12h2v5H7zm4-3h2v8h-2zm4-3h2v11h-2z"/>
                  </svg>
                </div>
                <div>
                  <h2 className="text-xl font-bold text-white">PowerPoint</h2>
                  <p className="text-orange-100">5-slide presentation</p>
                </div>
              </div>
            </div>

            <div className="p-6">
              <div className="border border-slate-600 rounded-lg p-4 mb-4 bg-slate-900/50">
                <h3 className="font-bold text-white mb-1">GLP1_Presentation.pptx</h3>
                <p className="text-sm text-slate-400 mb-3">Executive summary deck</p>
                <div className="flex items-center gap-4 text-xs text-slate-400">
                  <span>5 slides</span>
                  <span>HTML format</span>
                </div>
              </div>

              <h4 className="font-semibold text-slate-300 mb-3">Slides</h4>
              <ul className="space-y-2 mb-6">
                <li className="flex justify-between text-sm border-b border-slate-700 pb-2">
                  <span className="text-slate-300">Title & Key Metrics</span>
                </li>
                <li className="flex justify-between text-sm border-b border-slate-700 pb-2">
                  <span className="text-slate-300">Market Overview</span>
                </li>
                <li className="flex justify-between text-sm border-b border-slate-700 pb-2">
                  <span className="text-slate-300">Patent Landscape</span>
                </li>
                <li className="flex justify-between text-sm">
                  <span className="text-slate-300">Recommendations</span>
                </li>
              </ul>

              <button
                onClick={handleDownloadPPT}
                disabled={isGenerating !== null}
                className="w-full py-3 bg-orange-500 hover:bg-orange-600 text-white font-semibold rounded-lg transition disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
              >
                {isGenerating === 'ppt' ? (
                  <>
                    <svg className="animate-spin w-5 h-5" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                    </svg>
                    Generating...
                  </>
                ) : (
                  <>
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                    Download PPT
                  </>
                )}
              </button>
            </div>
          </div>
        </div>

        <div className="bg-slate-800/50 backdrop-blur-sm rounded-2xl shadow-xl p-8 border border-slate-700">
          <h2 className="text-2xl font-bold text-white mb-6 text-center">Report Preview</h2>
          
          <div className="bg-slate-900 rounded-lg p-6 max-w-4xl mx-auto border border-slate-600">
            <div className="bg-white rounded-lg shadow-lg overflow-hidden">
              <div className="bg-gradient-to-r from-indigo-600 to-cyan-600 p-6 text-white">
                <h3 className="text-2xl font-bold">{sampleReportData.title}</h3>
                <p className="opacity-80">{sampleReportData.subtitle}</p>
                <p className="text-sm mt-2 opacity-60">Generated by CureCoders AI | {sampleReportData.generatedDate}</p>
              </div>
              
              <div className="p-6 space-y-6">
                <div>
                  <h4 className="text-lg font-bold text-slate-800 mb-3">Executive Summary</h4>
                  <p className="text-slate-600 text-sm leading-relaxed">
                    The GLP-1 agonist market for obesity represents a $12.4B opportunity with 23.5% CAGR through 2030. 
                    Novo Nordisk currently dominates with 62% market share, but Eli Lilly's Tirzepatide shows superior 
                    efficacy data and is gaining ground. Key patent expirations in 2026 create opportunities for generic entry.
                  </p>
                </div>
                
                <div className="grid md:grid-cols-3 gap-4">
                  <div className="bg-blue-50 rounded-lg p-4 text-center">
                    <div className="text-2xl font-bold text-blue-600">$12.4B</div>
                    <div className="text-xs text-slate-500">Market Size 2024</div>
                  </div>
                  <div className="bg-green-50 rounded-lg p-4 text-center">
                    <div className="text-2xl font-bold text-green-600">23.5%</div>
                    <div className="text-xs text-slate-500">CAGR 2024-2030</div>
                  </div>
                  <div className="bg-purple-50 rounded-lg p-4 text-center">
                    <div className="text-2xl font-bold text-purple-600">47</div>
                    <div className="text-xs text-slate-500">Active Trials</div>
                  </div>
                </div>

                <div className="border-t border-slate-200 pt-4">
                  <p className="text-xs text-slate-400 text-center">
                    Page 1 of {sampleReportData.pages} | This is a preview of the full report
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="mt-12 bg-gradient-to-r from-indigo-900 to-cyan-900 rounded-2xl p-8 border border-indigo-500/30">
          <h2 className="text-2xl font-bold text-white mb-6">Report Generation Features</h2>
          <div className="grid md:grid-cols-4 gap-4">
            <div className="bg-white/5 rounded-lg p-4 border border-white/10">
              <h3 className="font-bold text-white mb-2">Auto-Layout</h3>
              <p className="text-sm text-slate-300">Professional templates with automatic formatting</p>
            </div>
            <div className="bg-white/5 rounded-lg p-4 border border-white/10">
              <h3 className="font-bold text-white mb-2">Multi-Agent Data</h3>
              <p className="text-sm text-slate-300">Synthesizes insights from all 7 worker agents</p>
            </div>
            <div className="bg-white/5 rounded-lg p-4 border border-white/10">
              <h3 className="font-bold text-white mb-2">Multiple Formats</h3>
              <p className="text-sm text-slate-300">Export as PDF, Excel, or PowerPoint</p>
            </div>
            <div className="bg-white/5 rounded-lg p-4 border border-white/10">
              <h3 className="font-bold text-white mb-2">Branded Output</h3>
              <p className="text-sm text-slate-300">Customizable with your company branding</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReportsDemo;
